baseURL = 'https://mitzvot.post-self.ink/'
languageCode = 'en-us'
title = 'Mitzvot'
theme = 'maddybook'
paginatePath = ''

[permalinks]
    post = '/:filename/'

[params]
    author = 'Madison Scott-Clary'
    home = 'https://makyo.ink'
    copyright = 2023
    customCSS = ['/css/mitzvot.css']
    subtitle = 'Post-Self book IV'
    subtitleLink = 'https://post-self.ink'

[markup.goldmark.renderer]
    unsafe = true
